### ISSUE TITLE
Version is not up to date while using the latest JDK

### ISSUE THREAD

**Issue by T-Lacerte** [shibadevs/phunk#4]
# Problem
When using the latest JDK (jdk-21) and with the app's default configuration, the app fails as soon as the start button is pressed. 
The error message in the textbox says: `[Phunk] Version is not up to date: 21.0`, while the error message at the bottom says: `Can't start the task because you having missing requirements: Java 8+`.
# Repro steps
1. Install the latest JDK available (jdk-21 at the moment this issue was written)
2. Open the app
3. Select an APK
4. Press the start button
5. Check for both error messages

![image](https://github.com/shibadevs/phunk/assets/110429590/1cdd5164-967b-48b2-90a6-488e1e633d55)

**Comment by Boorman76** [comment]
Hi, Same issue for me 
![image](https://github.com/shibadevs/phunk/assets/86838947/ced00713-e070-4acf-b1d1-534907be3af6)
![image](https://github.com/shibadevs/phunk/assets/86838947/0cabbcfc-fefc-4796-8f73-570b184eb16b)

Love the idea of this.  Really hope you can get it working.

**Comment by PabloKQ** [comment]
Same issuen here. Any solution?

**Comment by shibadevs** [comment]
I'm very sorry for the late reply. I already found the issue, and it was a merge conflict issue. It seems like I accidentally left out the merge conflict for the ReqChecker which is responsible for checking the Java version with the fixed version, and apparently, I forgot to compare and built Phunk with the unfixed version? I don't really know why it happened, but hopefully it will be all fixed by the next update. Thank you for helping Phunk get better.
